#!/bin/bash
# -----------------------------------------------------------------------------
# deploy_k3s.sh - Automated deployment script for FinOps Dashboard on k3s (RHEL 9.7)
# -----------------------------------------------------------------------------
set -e

echo "🚀 Starting FinOps Dashboard Deployment on k3s..."

# 1. Check for a container builder (Podman is native/default on RHEL 9)
BUILDER=""
if command -v podman &> /dev/null; then
    BUILDER="podman"
elif command -v docker &> /dev/null; then
    BUILDER="docker"
else
    echo "❌ Error: Neither 'podman' nor 'docker' is installed."
    echo "   Please install podman on RHEL 9 (sudo dnf install podman) to build the image."
    exit 1
fi

echo "📦 Using '$BUILDER' to build the container image (nginx:alpine-slim)..."

# 2. Build the image locally
$BUILDER build -t finops-dashboard:latest .

# 3. Export the image and import it directly into k3s containerd
# This bypasses the need for an external container registry
echo "🔄 Exporting image and importing into local k3s containerd..."
IMAGE_TAR="/tmp/finops-dashboard.tar"
$BUILDER save -o $IMAGE_TAR finops-dashboard:latest

# Note: Requires sudo to interact with k3s containerd socket
sudo k3s ctr images import $IMAGE_TAR
rm -f $IMAGE_TAR

# 4. Apply the Kubernetes manifest
echo "☸️ Applying Kubernetes manifests..."
if ! command -v kubectl &> /dev/null; then
    echo "⚠️ 'kubectl' not found in PATH. Ensure k3s is fully installed."
    echo "   To install k3s: curl -sfL https://get.k3s.io | sh -"
    exit 1
fi

kubectl apply -f k3s-dashboard.yaml

# 5. Wait for deployment and output access URL
echo "⏳ Waiting for deployment to be ready..."
kubectl rollout status deployment/finops-dashboard --timeout=60s

# Fetch the dynamic NodePort generated by k3s
NODE_PORT=$(kubectl get svc finops-dashboard-svc -o jsonpath='{.spec.ports[0].nodePort}')
NODE_IP=$(hostname -I | awk '{print $1}')

echo ""
echo "✅ Deployment Successful!"
echo "=========================================================="
echo "🌐 You can access the FinOps Dashboard at: http://${NODE_IP}:${NODE_PORT}"
echo "=========================================================="
